create table if not exists baby_names (
  id bigint generated always as identity primary key,
  name text not null,
  gender text not null check (gender in ('girl', 'boy', 'unisex')),
  origin text not null,
  meaning text not null
);

alter table baby_names enable row level security;

create policy "Public read access"
  on baby_names
  for select
  using (true);

insert into baby_names (name, gender, origin, meaning) values
  ('Alice', 'girl', 'Grec', 'De noble lignée'),
  ('Chloé', 'girl', 'Grec', 'Jeune pousse verdoyante'),
  ('Emma', 'girl', 'Germanique', 'Universelle, puissante'),
  ('Léa', 'girl', 'Hébreu', 'Gazelle'),
  ('Manon', 'girl', 'Provençal', 'Diminutif de Marie'),
  ('Sarah', 'girl', 'Hébreu', 'Princesse'),
  ('Julia', 'girl', 'Latin', 'Issue de la jeunesse'),
  ('Zoé', 'girl', 'Grec', 'La vie'),
  ('Inès', 'girl', 'Grec', 'Pure, chaste'),
  ('Louise', 'girl', 'Germanique', 'Célèbre guerrière'),
  ('Jade', 'girl', 'Espagnol', 'Pierre précieuse'),
  ('Lina', 'girl', 'Arabe', 'Douce, tendre'),
  ('Nour', 'girl', 'Arabe', 'Lumière'),
  ('Rose', 'girl', 'Latin', 'La fleur'),
  ('Hélène', 'girl', 'Grec', 'Le soleil'),
  ('Margot', 'girl', 'Grec', 'La perle'),
  ('Agathe', 'girl', 'Grec', 'La bonne'),
  ('Clara', 'girl', 'Latin', 'Claire, brillante'),
  ('Anna', 'girl', 'Hébreu', 'La grâce'),
  ('Léna', 'girl', 'Grec', 'La lumineuse'),
  ('Juliette', 'girl', 'Latin', 'Issue de la jeunesse'),
  ('Victoire', 'girl', 'Latin', 'La victoire'),
  ('Iris', 'girl', 'Grec', 'Arc-en-ciel'),
  ('Elsa', 'girl', 'Germanique', 'Dieu est ma promesse'),
  ('Alma', 'girl', 'Latin', 'Nourricière, généreuse'),
  ('Maya', 'girl', 'Sanskrit', 'Illusion, magie'),
  ('Capucine', 'girl', 'Latin', 'La fleur du même nom'),
  ('Violette', 'girl', 'Latin', 'Modestie, la fleur'),
  ('Constance', 'girl', 'Latin', 'La fidélité'),
  ('Éléonore', 'girl', 'Grec', 'Lumière du soleil'),
  ('Léo', 'boy', 'Latin', 'Le lion'),
  ('Hugo', 'boy', 'Germanique', 'Intelligence, esprit'),
  ('Gabriel', 'boy', 'Hébreu', 'Force de Dieu'),
  ('Raphaël', 'boy', 'Hébreu', 'Dieu guérit'),
  ('Louis', 'boy', 'Germanique', 'Célèbre guerrier'),
  ('Arthur', 'boy', 'Celtique', 'Ours, symbole de force'),
  ('Jules', 'boy', 'Latin', 'Issu de la jeunesse'),
  ('Nathan', 'boy', 'Hébreu', 'Il a donné'),
  ('Ethan', 'boy', 'Hébreu', 'Fort, robuste'),
  ('Noah', 'boy', 'Hébreu', 'Repos, consolation'),
  ('Adam', 'boy', 'Hébreu', 'Homme, terre'),
  ('Paul', 'boy', 'Latin', 'Petit, humble'),
  ('Victor', 'boy', 'Latin', 'Le vainqueur'),
  ('Antoine', 'boy', 'Latin', 'Inestimable'),
  ('Théo', 'boy', 'Grec', 'Don de Dieu'),
  ('Mathis', 'boy', 'Hébreu', 'Don de Dieu'),
  ('Simon', 'boy', 'Hébreu', 'Celui qui écoute'),
  ('Marc', 'boy', 'Latin', 'Consacré à Mars'),
  ('Oscar', 'boy', 'Scandinave', 'Lance divine'),
  ('Thomas', 'boy', 'Araméen', 'Le jumeau'),
  ('Alexandre', 'boy', 'Grec', 'Protecteur des hommes'),
  ('Baptiste', 'boy', 'Grec', 'Celui qui baptise'),
  ('Basile', 'boy', 'Grec', 'Le roi'),
  ('Clément', 'boy', 'Latin', 'Doux, clément'),
  ('Émile', 'boy', 'Latin', 'Ardent, rival'),
  ('Félix', 'boy', 'Latin', 'Heureux, chanceux'),
  ('Gaspard', 'boy', 'Perse', 'Gardien du trésor'),
  ('Ismaël', 'boy', 'Hébreu', 'Dieu écoute'),
  ('Marius', 'boy', 'Latin', 'Viril, guerrier'),
  ('Timothée', 'boy', 'Grec', 'Qui honore Dieu'),
  ('Camille', 'unisex', 'Latin', 'Jeune officiant religieux'),
  ('Charlie', 'unisex', 'Germanique', 'Homme libre'),
  ('Dominique', 'unisex', 'Latin', 'Qui appartient au Seigneur'),
  ('Alix', 'unisex', 'Grec', 'Protecteur, protectrice'),
  ('Noa', 'unisex', 'Hébreu', 'Mouvement, repos'),
  ('Sasha', 'unisex', 'Grec', 'Protecteur des hommes'),
  ('Ange', 'unisex', 'Grec', 'Le messager'),
  ('Claude', 'unisex', 'Latin', 'Qui avance avec prudence');
